import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Linkedin 2.0',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				{/* Toaster */}

				<header>{/* Header */}</header>

				<div>
					<main>{children}</main>
				</div>
			</body>
		</html>
	)
}
