import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
	title: 'Linkedin 2.0',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className="min-h-screen flex flex-col">
					{/* Toaster */}

					{/* Header  */}
					<header className="border-b sticky top-0 bg-white z-50">
						<Header />
					</header>

					<div className="bg-[#F4F2ED] flex-1 w-full">
						<main>{children}</main>
					</div>
				</body>
			</html>
		</ClerkProvider>
	)
}
